services:
  - type: web
    name: llm-api-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    pythonVersion: 3.11
    envVars:
      - key: OPENAI_API_KEY
        sync: false
