[project]
name = "llm-api-sdk-generator"
version = "0.1.0"
dependencies = [
  "fastapi==0.111.0",
  "uvicorn==0.30.1",
  "openai==1.55.3",
  "python-dotenv==1.0.1"
  "httpx==0.27.2"
]

[tool.uv]
virtualenvs.in-project = true

